#create dictionary
dictionary=dict({1:'abc',2:'xyz',3:'pqr'})
print(dictionary)
print(dictionary[2])
print(dictionary[5])
'''
{1: 'abc', 2: 'xyz', 3: 'pqr'}
xyz
Traceback (most recent call last):
  File "F:/19A91A0564/listException.py", line 16, in <module>
    print(dictionary[5])
KeyError: 5
'''
